-- SQLite
DROP TABLE Product_Data;
CREATE TABLE Product_Data (Id INTEGER PRIMARY KEY, brand TEXT, product TEXT, x3dModelTitle TEXT, x3dCreationMethod TEXT, modelTitle TEXT, modelSubtitle TEXT, modelDescription TEXT);

-- Fanta
INSERT INTO Product_Data (Id, brand, product, x3dModelTitle, x3dCreationMethod, modelTitle, modelSubtitle, modelDescription)
VALUES (1,'Fanta','apple','X3D Can Model','This model was created in blender and exported to .x3d format for interactive viewing','Fanta Apple','Its a know what you like green apple fav flavor on repeat classics were new once its not a fad if it means something find your place all your places thing.','INGREDIANTS : CARBONATED WATER, HIGH FRUCTOSE CORN SYRUP, NATURAL FLAVORS, CITRIC ACID, MALIC ACID, CARAMEL COLOR, SODIUM CITRATE, SODIUM BENZOATE AND POTASSIUM SORBATE (TO PROTECT TASTE).');
INSERT INTO Product_Data (Id, brand, product, x3dModelTitle, x3dCreationMethod, modelTitle, modelSubtitle, modelDescription)
VALUES (2,'Fanta','grape','X3D Can Model','This model was created in blender and exported to .x3d format for interactive viewing','Fanta Grape','Its a speak out stand out tricked out self-expression is the only expression fresh flavor fashion with a side of glam grape thing.','"INGREDIANTS : CARBONATED WATER, HIGH FRUCTOSE CORN SYRUP, NATURAL FLAVORS, TARTARIC ACID, POTASSIUM SORBATE AND SODIUM BENZOATE (TO PROTECT TASTE), CITRIC ACID, RED 40, BLUE 1."');
INSERT INTO Product_Data (Id, brand, product, x3dModelTitle, x3dCreationMethod, modelTitle, modelSubtitle, modelDescription)
VALUES (3,'Fanta','orange','X3D Can Model','This model was created in blender and exported to .x3d format for interactive viewing','Fanta Orange','Its a classic iconic flavor inspiration in a bottle passion for life share every moment because embracing what makes you unique makes you cool thing.','"INGREDIANTS : CARBONATED WATER, HIGH FRUCTOSE CORN SYRUP, CITRIC ACID, SODIUM BENZOATE (TO PROTECT TASTE), NATURAL FLAVORS, MODIFIED FOOD STARCH, SODIUM POLYPHOSPHATES, GLYCEROL ESTER OF ROSIN, YELLOW 6, RED 40."');
INSERT INTO Product_Data (Id, brand, product, x3dModelTitle, x3dCreationMethod, modelTitle, modelSubtitle, modelDescription)
VALUES (4,'Fanta','pineapple','X3D Can Model','This model was created in blender and exported to .x3d format for interactive viewing','Fanta Pineapple','Its a bold confident never settle flavor high score you do you and dont apologize for leveling up your 8-bit love of pineapple thing.','"INGREDIANTS : CARBONATED WATER, HIGH FRUCTOSE CORN SYRUP, CITRIC ACID, NATURAL FLAVORS, MODIFIED FOOD STARCH, POTASSIUM SORBATE AND SODIUM BENZOATE (TO PROTECT TASTE), SODIUM CITRATE, MEDIUM CHAIN TRIGLYCERIDES, SALT, SUCROSE ACETATE ISOBUTYRATE, YELLOW 5, YELLOW 6."');
INSERT INTO Product_Data (Id, brand, product, x3dModelTitle, x3dCreationMethod, modelTitle, modelSubtitle, modelDescription)
VALUES (5,'Fanta','strawberry','X3D Can Model','This model was created in blender and exported to .x3d format for interactive viewing','Fanta Strawberry','Its a low key chill spontaneous strawberry hang under the radar flavor make the most of every vaporwave daydream thing.','"INGREDIANTS : CARBONATED WATER, HIGH FRUCTOSE CORN SYRUP, NATURAL FLAVORS, CITRIC ACID, SODIUM BENZOATE (TO PROTECT TASTE), RED 40."');

-- Schweppes
INSERT INTO Product_Data (Id, brand, product, x3dModelTitle, x3dCreationMethod, modelTitle, modelSubtitle, modelDescription)
VALUES (6,'Schweppes','bitterlemon','X3D Can Model','This model was created in blender and exported to .x3d format for interactive viewing','Schweppes Bitter Lemon','Great with Gin and Tonic!','"Delivering its distinctive bittersweet bite for over 60 years, Schweppes Bitter Lemon was created in London in 1957. It is crafted with a complex blend of orange and lemon peels, harnessing a blend of lemon juice and bespoke citrus essences and oils sourced from around the world. Finally, it is finished with a touch of quinine from the tropics, derived from the bark of the cinchona tree."');
INSERT INTO Product_Data (Id, brand, product, x3dModelTitle, x3dCreationMethod, modelTitle, modelSubtitle, modelDescription)
VALUES (7,'Schweppes','citrusmix','X3D Can Model','This model was created in blender and exported to .x3d format for interactive viewing','Schweppes Citrus Mix','Great with Gin and Tonic!','"Refined taste of orange, grapefruit, lime and mandarin in a sophisticated drink with character."');
INSERT INTO Product_Data (Id, brand, product, x3dModelTitle, x3dCreationMethod, modelTitle, modelSubtitle, modelDescription)
VALUES (8,'Schweppes','gingerale','X3D Can Model','This model was created in blender and exported to .x3d format for interactive viewing','Schweppes Ginger Ale','Suitable for non-alcoholics!','"The soda with a refreshing ginger taste, refined since 1870. A classic that never ceases to surprise."');
INSERT INTO Product_Data (Id, brand, product, x3dModelTitle, x3dCreationMethod, modelTitle, modelSubtitle, modelDescription)
VALUES (9,'Schweppes','bitterlemon','X3D Bottle Model','This model was created in blender and exported to .x3d format for interactive viewing','Schweppes Bitter Lemon','Great with Gin and Tonic!','"Delivering its distinctive bittersweet bite for over 60 years, Schweppes Bitter Lemon was created in London in 1957. It is crafted with a complex blend of orange and lemon peels, harnessing a blend of lemon juice and bespoke citrus essences and oils sourced from around the world. Finally, it is finished with a touch of quinine from the tropics, derived from the bark of the cinchona tree."');
INSERT INTO Product_Data (Id, brand, product, x3dModelTitle, x3dCreationMethod, modelTitle, modelSubtitle, modelDescription)
VALUES (10,'Schweppes','citrusmix','X3D Bottle Model','This model was created in blender and exported to .x3d format for interactive viewing','Schweppes Citrus Mix','Great with Gin and Tonic!','"Refined taste of orange, grapefruit, lime and mandarin in a sophisticated drink with character."');
INSERT INTO Product_Data (Id, brand, product, x3dModelTitle, x3dCreationMethod, modelTitle, modelSubtitle, modelDescription)
VALUES (11,'Schweppes','lemon','X3D Bottle Model','This model was created in blender and exported to .x3d format for interactive viewing','Schweppes Lemon','A true British classic!','"The most thirst-quenching drinking sensation with typical Schweppes bite: a unique blend of lemon juice and lemon rind for a rich, balanced taste. Fresh and tangy flavour"');
INSERT INTO Product_Data (Id, brand, product, x3dModelTitle, x3dCreationMethod, modelTitle, modelSubtitle, modelDescription)
VALUES (12,'Schweppes','indian','X3D Bottle Model','This model was created in blender and exported to .x3d format for interactive viewing','Schweppes Indian Tonic','Required reading for the over 40s','"Born over 145 years ago in 1870, Schweppes Indian Tonic Water is created using carefully selected lemons and oranges, which are gently peeled, steeped and cold pressed to release their oils. These oils are then combined with quinine derived from the bark of the cinchona tree from tropical plantations, creating a tonic water thats second to none."');

-- Misc
INSERT INTO Product_Data (Id, brand, product, x3dModelTitle, x3dCreationMethod, modelTitle, modelSubtitle, modelDescription)
VALUES (13,'Coca Cola','coke','X3D Can Model','This model was created in blender and exported to .x3d format for interactive viewing','Coca Cola','The original taste','Coca‑Cola Original Taste is the worlds favourite soft drink and has been enjoyed since 1886. You can find Coca‑Cola Original Taste in a variety of sizes to suit every lifestyle and occasion.');
INSERT INTO Product_Data (Id, brand, product, x3dModelTitle, x3dCreationMethod, modelTitle, modelSubtitle, modelDescription)
VALUES (14,'Coca Cola','dietcoke','X3D Can Model','This model was created in blender and exported to .x3d format for interactive viewing','Diet Coke','The lighter flavour','"History was made 40 years ago with the creation of Diet Coke. Within two years, Diet Coke was the worlds favourite light cola, and it still is! Diet Coke encourages you to love what you love, celebrating the unapologetic attitude that comes with knowing who you are and what youre into, whether its cool or not. So add some sparkle to your day - without sugar or calories - with a crisp, refreshing Diet Coke!"');
INSERT INTO Product_Data (Id, brand, product, x3dModelTitle, x3dCreationMethod, modelTitle, modelSubtitle, modelDescription)
VALUES (15,'Dr Pepper','drpepper','X3D Can Model','This model was created in blender and exported to .x3d format for interactive viewing','Dr Pepper','"I dont know what it is, but I like it!"','"For over a century, Dr Peppers truly unique taste has been impossible to describe… a taste so misunderstood thats confusingly good. Grab it now, thank us later. Available with zero sugar and zero calories. So odd, so good, So MiSuNderStoOd®​"');
